from PyQt5 import QtCore, QtWidgets
from mycombox import MyComboBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        MainWindow.setMinimumSize(QtCore.QSize(400, 600))
        MainWindow.setMaximumSize(QtCore.QSize(400, 600))
        MainWindow.setStyleSheet("background-color: rgb(58, 64, 80);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(90, 30))
        self.label.setMaximumSize(QtCore.QSize(90, 30))
        self.label.setStyleSheet('font: 22px "Microsoft YaHei";\ncolor: white;')
        
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.deviceCBox = MyComboBox(self.centralwidget)
        self.deviceCBox.setMinimumSize(QtCore.QSize(105, 30))
        self.deviceCBox.setMaximumSize(QtCore.QSize(105, 30))
        self.deviceCBox.setStyleSheet('background-color: rgb(50, 55, 62);\n color: white;\n border-radius: 5px;\n font-size: 16px;\nfont-family:"Microsoft YaHei";')
        
        self.deviceCBox.setObjectName("deviceCBox")
        self.gridLayout.addWidget(self.deviceCBox, 0, 2, 1, 1)
        self.bt_open = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.bt_open.sizePolicy().hasHeightForWidth())
        self.bt_open.setSizePolicy(sizePolicy)
        self.bt_open.setMinimumSize(QtCore.QSize(70, 30))
        self.bt_open.setMaximumSize(QtCore.QSize(70, 30))
        self.bt_open.setStyleSheet('QPushButton {\n                background-color: #409eff;\n                color: white;\n                border-radius: 5px;\n                font-size: 20px;\n                font-family:\\"Microsoft YaHei\\";}\n                \n                QPushButton:hover {background-color: #66b1ff;}\n\n                QPushButton:pressed {background-color: #3a8ee6;}\n        \n                QPushButton:disabled {\n                background-color: #cccccc;\n                color: #888888;}')
        
        self.bt_open.setObjectName("bt_open")
        self.gridLayout.addWidget(self.bt_open, 0, 3, 1, 1)
        self.bt_close = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(70)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.bt_close.sizePolicy().hasHeightForWidth())
        self.bt_close.setSizePolicy(sizePolicy)
        self.bt_close.setMinimumSize(QtCore.QSize(70, 30))
        self.bt_close.setMaximumSize(QtCore.QSize(70, 30))
        self.bt_close.setStyleSheet('QPushButton {\n                background-color: #409eff;\n                color: white;\n                border-radius: 5px;\n                font-size: 20px;\n                font-family:\\"Microsoft YaHei\\";}\n                \n                QPushButton:hover {background-color: #66b1ff;}\n\n                QPushButton:pressed {background-color: #3a8ee6;}\n        \n                QPushButton:disabled {\n                background-color: #cccccc;\n                color: #888888;}')
        
        self.bt_close.setObjectName("bt_close")
        self.gridLayout.addWidget(self.bt_close, 0, 4, 1, 1)
        self.rb_manual = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_manual.setStyleSheet('font: 22px "Microsoft YaHei";\ncolor: white;')
        
        self.rb_manual.setChecked(True)
        self.rb_manual.setObjectName("rb_manual")
        self.gridLayout.addWidget(self.rb_manual, 1, 0, 1, 3)
        self.bt_back = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.bt_back.sizePolicy().hasHeightForWidth())
        self.bt_back.setSizePolicy(sizePolicy)
        self.bt_back.setMinimumSize(QtCore.QSize(80, 30))
        self.bt_back.setMaximumSize(QtCore.QSize(70, 30))
        self.bt_back.setStyleSheet('QPushButton {\n                background-color: #409eff;\n                color: white;\n                border-radius: 5px;\n                font-size: 20px;\n                font-family:\\"Microsoft YaHei\\";}\n                \n                QPushButton:hover {background-color: #66b1ff;}\n\n                QPushButton:pressed {background-color: #3a8ee6;}\n        \n                QPushButton:disabled {\n                background-color: #cccccc;\n                color: #888888;}')
        
        self.bt_back.setObjectName("bt_back")
        self.gridLayout.addWidget(self.bt_back, 2, 0, 1, 1)
        self.edit_back = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_back.setMinimumSize(QtCore.QSize(80, 30))
        self.edit_back.setMaximumSize(QtCore.QSize(80, 30))
        self.edit_back.setStyleSheet('background-color: rgb(50, 55, 62); color: white; border-radius: 5px; font-size: 20px;font-family:"Microsoft YaHei";')
        self.edit_back.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.edit_back.setObjectName("edit_back")
        self.gridLayout.addWidget(self.edit_back, 2, 1, 1, 2)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(50, 30))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(50, 30))
        self.lineEdit_5.setStyleSheet('background-color: rgb(58, 64, 80); color: white; border-radius: 5px; font-size: 20px;font-family:"Microsoft YaHei";')
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(107, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 4, 1, 1)
        self.bt_fwr = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.bt_fwr.sizePolicy().hasHeightForWidth())
        self.bt_fwr.setSizePolicy(sizePolicy)
        self.bt_fwr.setMinimumSize(QtCore.QSize(80, 30))
        self.bt_fwr.setMaximumSize(QtCore.QSize(70, 30))
        self.bt_fwr.setStyleSheet('QPushButton {\n                background-color: #409eff;\n                color: white;\n                border-radius: 5px;\n                font-size: 20px;\n                font-family:\\"Microsoft YaHei\\";}\n                \n                QPushButton:hover {background-color: #66b1ff;}\n\n                QPushButton:pressed {background-color: #3a8ee6;}\n        \n                QPushButton:disabled {\n                background-color: #cccccc;\n                color: #888888;}')
        
        self.bt_fwr.setObjectName("bt_fwr")
        self.gridLayout.addWidget(self.bt_fwr, 3, 0, 1, 1)
        self.edit_fwr = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_fwr.setMinimumSize(QtCore.QSize(80, 30))
        self.edit_fwr.setMaximumSize(QtCore.QSize(80, 30))
        self.edit_fwr.setStyleSheet('background-color: rgb(50, 55, 62); color: white; border-radius: 5px; font-size: 20px;font-family:"Microsoft YaHei";')
        self.edit_fwr.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.edit_fwr.setObjectName("edit_fwr")
        self.gridLayout.addWidget(self.edit_fwr, 3, 1, 1, 2)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(50, 30))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(50, 30))
        self.lineEdit_6.setStyleSheet('background-color: rgb(58, 64, 80); color: white; border-radius: 5px; font-size: 20px;font-family:"Microsoft YaHei";')
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 3, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(107, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 4, 1, 1)
        self.bt_lturn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.bt_lturn.sizePolicy().hasHeightForWidth())
        self.bt_lturn.setSizePolicy(sizePolicy)
        self.bt_lturn.setMinimumSize(QtCore.QSize(80, 30))
        self.bt_lturn.setMaximumSize(QtCore.QSize(70, 30))
        self.bt_lturn.setStyleSheet('QPushButton {\n                background-color: #409eff;\n                color: white;\n                border-radius: 5px;\n                font-size: 20px;\n                font-family:\\"Microsoft YaHei\\";}\n                \n                QPushButton:hover {background-color: #66b1ff;}\n\n                QPushButton:pressed {background-color: #3a8ee6;}\n        \n                QPushButton:disabled {\n                background-color: #cccccc;\n                color: #888888;}')
        
        self.bt_lturn.setObjectName("bt_lturn")
        self.gridLayout.addWidget(self.bt_lturn, 4, 0, 1, 1)
        self.edit_lturn = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_lturn.setMinimumSize(QtCore.QSize(80, 30))
        self.edit_lturn.setMaximumSize(QtCore.QSize(80, 30))
        self.edit_lturn.setStyleSheet('background-color: rgb(50, 55, 62); color: white; border-radius: 5px; font-size: 20px;font-family:"Microsoft YaHei";')
        self.edit_lturn.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.edit_lturn.setObjectName("edit_lturn")
        self.gridLayout.addWidget(self.edit_lturn, 4, 1, 1, 2)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(50, 30))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(50, 30))
        self.lineEdit_7.setStyleSheet('background-color: rgb(58, 64, 80); color: white; border-radius: 5px; font-size: 20px;font-family:"Microsoft YaHei";')
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 4, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(107, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 4, 1, 1)
        self.bt_rturn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.bt_rturn.sizePolicy().hasHeightForWidth())
        self.bt_rturn.setSizePolicy(sizePolicy)
        self.bt_rturn.setMinimumSize(QtCore.QSize(80, 30))
        self.bt_rturn.setMaximumSize(QtCore.QSize(70, 30))
        self.bt_rturn.setStyleSheet('QPushButton {\n                background-color: #409eff;\n                color: white;\n                border-radius: 5px;\n                font-size: 20px;\n                font-family:\\"Microsoft YaHei\\";}\n                \n                QPushButton:hover {background-color: #66b1ff;}\n\n                QPushButton:pressed {background-color: #3a8ee6;}\n        \n                QPushButton:disabled {\n                background-color: #cccccc;\n                color: #888888;}')
        
        self.bt_rturn.setObjectName("bt_rturn")
        self.gridLayout.addWidget(self.bt_rturn, 5, 0, 1, 1)
        self.edit_rturn = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_rturn.setMinimumSize(QtCore.QSize(80, 30))
        self.edit_rturn.setMaximumSize(QtCore.QSize(80, 30))
        self.edit_rturn.setStyleSheet('background-color: rgb(50, 55, 62); color: white; border-radius: 5px; font-size: 20px;font-family:"Microsoft YaHei";')
        self.edit_rturn.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.edit_rturn.setObjectName("edit_rturn")
        self.gridLayout.addWidget(self.edit_rturn, 5, 1, 1, 2)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(50, 30))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(50, 30))
        self.lineEdit_8.setStyleSheet('background-color: rgb(58, 64, 80); color: white; border-radius: 5px; font-size: 20px;font-family:"Microsoft YaHei";')
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 5, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(107, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 4, 1, 1)
        self.bt_sound = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.bt_sound.sizePolicy().hasHeightForWidth())
        self.bt_sound.setSizePolicy(sizePolicy)
        self.bt_sound.setMinimumSize(QtCore.QSize(80, 30))
        self.bt_sound.setMaximumSize(QtCore.QSize(70, 30))
        self.bt_sound.setStyleSheet('QPushButton {\n                background-color: #409eff;\n                color: white;\n                border-radius: 5px;\n                font-size: 20px;\n                font-family:\\"Microsoft YaHei\\";}\n                \n                QPushButton:hover {background-color: #66b1ff;}\n\n                QPushButton:pressed {background-color: #3a8ee6;}\n        \n                QPushButton:disabled {\n                background-color: #cccccc;\n                color: #888888;}')
        
        self.bt_sound.setObjectName("bt_sound")
        self.gridLayout.addWidget(self.bt_sound, 6, 0, 1, 1)
        self.bt_flash = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.bt_flash.sizePolicy().hasHeightForWidth())
        self.bt_flash.setSizePolicy(sizePolicy)
        self.bt_flash.setMinimumSize(QtCore.QSize(80, 30))
        self.bt_flash.setMaximumSize(QtCore.QSize(70, 30))
        self.bt_flash.setStyleSheet('QPushButton {\n                background-color: #409eff;\n                color: white;\n                border-radius: 5px;\n                font-size: 20px;\n                font-family:\\"Microsoft YaHei\\";}\n                \n                QPushButton:hover {background-color: #66b1ff;}\n\n                QPushButton:pressed {background-color: #3a8ee6;}\n        \n                QPushButton:disabled {\n                background-color: #cccccc;\n                color: #888888;}')
        
        self.bt_flash.setObjectName("bt_flash")
        self.gridLayout.addWidget(self.bt_flash, 7, 0, 1, 1)
        self.rb_ssvep = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_ssvep.setMinimumSize(QtCore.QSize(160, 25))
        self.rb_ssvep.setMaximumSize(QtCore.QSize(160, 25))
        self.rb_ssvep.setStyleSheet('font: 22px "Microsoft YaHei";\ncolor: white;')
        
        self.rb_ssvep.setChecked(False)
        self.rb_ssvep.setObjectName("rb_ssvep")
        self.gridLayout.addWidget(self.rb_ssvep, 8, 0, 1, 3)
        self.bt_startssvep = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.bt_startssvep.sizePolicy().hasHeightForWidth())
        self.bt_startssvep.setSizePolicy(sizePolicy)
        self.bt_startssvep.setMinimumSize(QtCore.QSize(80, 30))
        self.bt_startssvep.setMaximumSize(QtCore.QSize(70, 30))
        self.bt_startssvep.setStyleSheet('QPushButton {\n                background-color: #409eff;\n                color: white;\n                border-radius: 5px;\n                font-size: 20px;\n                font-family:\\"Microsoft YaHei\\";}\n                \n                QPushButton:hover {background-color: #66b1ff;}\n\n                QPushButton:pressed {background-color: #3a8ee6;}\n        \n                QPushButton:disabled {\n                background-color: #cccccc;\n                color: #888888;}')
        
        self.bt_startssvep.setObjectName("bt_startssvep")
        self.gridLayout.addWidget(self.bt_startssvep, 8, 3, 1, 2)
        self.rb_ssvepvehicle = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_ssvepvehicle.setMinimumSize(QtCore.QSize(200, 25))
        self.rb_ssvepvehicle.setMaximumSize(QtCore.QSize(200, 25))
        self.rb_ssvepvehicle.setStyleSheet('font: 22px "Microsoft YaHei";\ncolor: white;')
        
        self.rb_ssvepvehicle.setObjectName("rb_ssvepvehicle")
        self.gridLayout.addWidget(self.rb_ssvepvehicle, 9, 0, 1, 3)
        self.bt_startssvepvehicle = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.bt_startssvepvehicle.sizePolicy().hasHeightForWidth())
        self.bt_startssvepvehicle.setSizePolicy(sizePolicy)
        self.bt_startssvepvehicle.setMinimumSize(QtCore.QSize(80, 30))
        self.bt_startssvepvehicle.setMaximumSize(QtCore.QSize(70, 30))
        self.bt_startssvepvehicle.setStyleSheet('QPushButton {\n                background-color: #409eff;\n                color: white;\n                border-radius: 5px;\n                font-size: 20px;\n                font-family:\\"Microsoft YaHei\\";}\n                \n                QPushButton:hover {background-color: #66b1ff;}\n\n                QPushButton:pressed {background-color: #3a8ee6;}\n        \n                QPushButton:disabled {\n                background-color: #cccccc;\n                color: #888888;}')
        
        self.bt_startssvepvehicle.setObjectName("bt_startssvepvehicle")
        self.gridLayout.addWidget(self.bt_startssvepvehicle, 9, 3, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "小车端口："))
        self.bt_open.setText(_translate("MainWindow", "打开"))
        self.bt_close.setText(_translate("MainWindow", "关闭"))
        self.rb_manual.setText(_translate("MainWindow", "手动调试小车"))
        self.bt_back.setText(_translate("MainWindow", "后退"))
        self.edit_back.setText(_translate("MainWindow", "5"))
        self.lineEdit_5.setText(_translate("MainWindow", "秒"))
        self.bt_fwr.setText(_translate("MainWindow", "前进"))
        self.edit_fwr.setText(_translate("MainWindow", "5"))
        self.lineEdit_6.setText(_translate("MainWindow", "秒"))
        self.bt_lturn.setText(_translate("MainWindow", "左转"))
        self.edit_lturn.setText(_translate("MainWindow", "5"))
        self.lineEdit_7.setText(_translate("MainWindow", "秒"))
        self.bt_rturn.setText(_translate("MainWindow", "右转"))
        self.edit_rturn.setText(_translate("MainWindow", "5"))
        self.lineEdit_8.setText(_translate("MainWindow", "秒"))
        self.bt_sound.setText(_translate("MainWindow", "鸣笛"))
        self.bt_flash.setText(_translate("MainWindow", "亮灯"))
        self.rb_ssvep.setText(_translate("MainWindow", "测试SSVEP"))
        self.bt_startssvep.setText(_translate("MainWindow", "启动"))
        self.rb_ssvepvehicle.setText(_translate("MainWindow", "SSVEP + 小车"))
        self.bt_startssvepvehicle.setText(_translate("MainWindow", "启动"))
